# This is a basic workflow to help you get started with Actions

name: Upload Files

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
    - 'files/**/*'
  pull_request:
    branches: [ ]  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  ab_1: ${{secrets.TEST_SECRET}}
  HMAC_SECRET: ${{secrets.DEVOPS_HMAC_SECRET}}
  HMAC_ACCESS_KEY: ${{secrets.DEVOPS_HMAC_ACCESS_KEY}}
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
    container: us-central1-docker.pkg.dev/kyndryl-platform-dev/kyndryl-p-repository/base-runner-image:0.3.4
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: kyndryl-platform/devops-custom-actions/download-scripts@main
      - uses: kyndryl-platform/devops-custom-actions/set-default-variables@main
      - uses: kyndryl-platform/devops-custom-actions/bridge-upload-folder@main
        env:
          DEVOPS_FILE_LOCAL_TARGET_FOLDER: files
          DEVOPS_BUCKET_TARGET: console-ui
          DEVOPS_FILE_TARGET_FOLDER: sustainability-advisor-contributions
